<?php

return [
    'Contacts' => 'Контакты',
    'Leave a request' => 'Оставить заявку',
    'Stages of development' => 'Этапы разработки',
    'Professional ethics' => 'Проффесиональная этика',
    'Advantages' => 'Преимущества',
    'Customers' => 'Клиенты',
    'Smart collection' => 'Интеллектуальная коллекция',
    'Technical support' => 'Техническая поддержка',
    'SAAS projects' => 'SAAS проекты',
    'Artificial intelligence' => 'Искусственный интеллект',
    'API Gateways' => 'Шлюзы API',
    'Smart watches' => 'Умные часы',
    'Mobile Applications' => 'Мобильные приложений',
    'Cloud solutions' => 'Облачнные решения',
    'Website development' => 'Разработка сайта',
    'Databases' => 'Базы данных',
    'CRM/ERP/HRM' => 'CRM/ERP/HRM',
    'Automation of business processes' => 'Автоматизация бизнес процессов',
    'Services' => 'Услуги',
    'About us' => 'О нас',
    'Vice - International IT company' => 'Visce - Международная IT компания',
    'Discuss the project' => 'Обсудить проект',
    'The best in their field' => 'Лучшие в своем деле',
    'A rapidly progressing company providing services for the automation of business processes and qualified application development. Over a long period of cooperation with various companies, we have been able to prove ourselves as professionals in our field. By contacting us, you will get peace of mind and confidence, which is why we have customers with whom cooperation has been going on for years and we mutually appreciate such relationships.' => 'Быстропрогресирующая компания, предоставляющая услуги по автоматизации бизнес процессов и квалифицированной разработки приложений. На протяжении длительного сотрудничества с различными компаниями мы смогли себя зарекомендовать как профессионалами в своем деле. Обращаясь к нам вы получите спокойствие и уверенность, именно поэтому у нас есть заказчики, сотрудничество с которыми длится уже годами и мы обоюдно ценим такие отношения.',
    'Our services' => 'Наши услуги',
    'CRM systems' => 'CRM - системы',
    'Database development' => 'Разработка баз данных',
    'Mobile applications' => 'Мобильные приложения',
    'Cloud solution' => 'Облачное решение',
    'API Integration' => 'Интеграция API',
    'Technical audit' => 'Технический аудит',
    'All services' => 'Все услуги',
    'The accumulated experience based on long-term cooperation with companies engaged in various activities allows us to successfully perform a full cycle of work - from initial requirements analysis and technology consulting to long-term support of implemented solutions.' => 'Накопленный опыт на основе долгосрочного сотрудничества с компаниями, занимающиеся различной деятельностью, позволяет успешно выполнять полный цикл работ - от начального анализа требований и технологического консалтинга до долговременной поддержки внедренных решений.',
    'Protection of personal data, confidential information, as well as ensuring business continuity. Unique experience in the field of information security, the ability to solve non-standard and large-scale tasks.' => 'Защита персональных данных, конфиденциальной информации, а также обеспечение непрерывности бизнеса. Уникальный опыт в области защиты информации, возможность решать нестандартные и масштабные задачи.',
    'We always take into account the needs of our partners and are ready to work on new projects to expand business opportunities.' => 'Мы всегда учитываем потребности партнеров и готовы работать над новыми проектами для расширения бизнес возможностей.',
    'Step into the future' => 'Шаг в будущее',
    'Interaction with clients' => 'Взаимодействие с клиентами',
    'Analysis' => 'Анализ',
    'We will consult and define your goals and objectives, determine the necessary basic functionality for a quick check of your business model.' => 'Проконсультируем и определим ваши цели и задачи,  определим необходимый базовый функционал для быстрой проверки вашей бизнес-модели.',
    'We will fix the desired functionality, send it to our analysts to compile a preliminary commercial offer for each of the stages of the creation / development of the project.' => 'Зафиксируем желаемый функционал, отправим нашим аналитикам  для составления предварительного коммерческого предложения на каждый из этапов создания/развития проекта.',
    'Designing' => 'Проектирование',
    'Based on our rich experience, we will propose best practices and solutions, reproduce the structure of the service and then jointly think through the main scenarios.' => 'На основе богатого опыта предложим лучшие практики и решения, воспроизведем структуру сервиса и затем совместно продумаем основные сценарии.',
    'A preliminary commercial offer will allow you to take into account as many details as possible, thereby saving hours at further stages.' => 'Предварительное коммерческое предложение позволит учесть максимум мелочей, тем самым сэкономить часы на дальнейших этапах.',
    'Development' => 'Разработка',
    'Together we will analyze the TOR, if changes are required, we will make adjustments to the documentation, give final estimates of the stages in terms of time and cost.' => 'Вместе разберем ТЗ, если потребуются изменения — внесём корректировки в документацию, дадим итоговые оценки этапов по времени и стоимости.',
    'We will assemble a team from our employees responsible for product development, draw up and sign the necessary documents (contracts and annexes with estimates).' => 'Соберём из наших сотрудников команду, ответственную за разработку продукта, составим и подпишем необходимые документы (договоры и приложения со сметами).',
    'We will contact you the next business day and advise you on all issues.' => 'Мы свяжемся с вами на следующий рабочий день и проконсультируем по всем вопросам.',
    'Name' => 'Имя',
    'Phone' => 'Телефон',
    'Content' => 'Содержание',
    'Tell us about your project...' => 'Расскажите о Вашем проекте...',
    'Send' => 'Отправить',
    'By submitting an application, you consent to the processing of your personal data.' => 'Оставляя заявку, Вы даете согласие на обработку Ваших персональных данных.',
    'Join us' => 'Присоединяйтесь к нам',
    'About the company' => 'О компании',
    'Work' => 'Работа',
    'Cookies' => 'Файлы Cookie',
    'Privacy Policy' => 'Политика конфиденциальности',
    'The main task of the business is to increase profits, and optimization of business processes at the enterprise is one of the ways to achieve this goal. The process approach, which is the basis of the Visce business process automation system, provides for optimization as an integral component of the company\'s development and a means of maintaining a leading position in a competitive environment.' => 'Главная задача бизнеса - увеличение прибыли, и оптимизация бизнес-процессов на предприятии - один из способов достижения этой цели. Процессный подход, который лежит в основе системы автоматизации бизнес-процессов Visce , предусматривает оптимизацию, как неотъемлемую составляющую развития компании и средство сохранения лидирующих позиций в конкурентной среде.',
    'To order' => 'Заказать',
    'They help to get up-to-date information and make timely management decisions based on it' => 'Помогают получать акутальную информацию и на ее основании принимать своевременные управленческие решения',
    'They allow you to increase sales and profits by working with customers correctly' => 'Позволяют увеличить объемы продаж и прибыль за счет правильной работы с клиентами',
    'They allow you to save staff from routine tasks and help reduce the influence of the human factor' => 'Позволяют избавить персонал от рутинных задач и опмогают снизить влияние человеческого фактора',
    'Development and implementation of CRM/ERP/HRM systems' => 'Разработка и внедрение CRM/ERP/HRM систем',
    'CRM is a customer relationship automation program that allows you to successfully control, plan and develop any customer–oriented business.' => 'CRM – это программа автоматизации отношений с покупателями, позволяющая успешно контролировать, планировать и развивать любой клиентоориентированный бизнес.',
    'ERP is a system aimed at managing the company\'s resources. The program allows you to exchange information and distribute tasks between departments.' => 'ERP — это система, направленная на управление ресурсами компании. Программа позволяет обмениваться информацией и распределять задачи между отделами.',
    'HRM is a program for personnel management. It allows you to track personnel decisions, evaluate the effectiveness of staff work and see motivation.' => 'HRM  — программа для управления персоналом. Позволяет отследить кадровые решения, оценить эффективность работы персонала и увидеть мотивацию.',
    'Reducing the influence of the human factor' => 'Сокращение влияния человеческого фактора',
    'Reduction of production costs' => 'Сокращение издержек производства',
    'Improving the company\'s manageability indicators' => 'Улучшение показателей управляемости компании',
    'Any software product works with information that can be in one form or another and is recorded in the data. Currently, it is generally accepted to present such information in the form of a set of independent systematized materials — a database. This allows you to store a large amount of information and quickly search for the right materials.' => 'Любой программный продукт работает с информацией, которая может находиться в той или иной форме и зафиксирована в данных. В настоящее время общепринято представлять такую информацию в виде набора самостоятельных систематизированных материалов — базы данных. Это позволяет хранить большой объем информации и осуществлять достаточно быстрый поиск нужных материалов.',
    'a single information space for all employees of the company' => 'единое информационное пространство для всех сотрудников компании',
    'a clear picture of the cases without spending time on preparing reports' => 'четкая картина дел без затрат времени на подготовку отчетов',
    'databases are better protected from information loss' => 'базы данных лучше защищены от потерь информации',
    'Cloud software development is an excellent solution for a company that needs an application or program with advanced user settings, good scalability and easy integration with the server.' => 'Разработка облачного программного обеспечения — это превосходное решение для компании, которой необходимо приложение или программа с расширенными пользовательскими настройками, хорошей масштабируемостью и легкой интегрирацией с сервером.',
    'You can store data and programs in cloud storage, working with them online and without loading your computer\'s hard drives.' => 'Вы можете хранить данные и программы в облачном хранилище, работая с ними в онлайн режиме и не нагружая жесткие диски своего компьютера.',
    'Work with text, tables and presentations together with colleagues' => 'Работайте с текстом, таблицами и презентациями совместно с коллегами',
    'allow and prohibit viewing and editing files to any user' => 'разрешайте и запрещайте просмотр и редактирование файлов любому пользователю',
    'You can view documents, images and videos directly in the browser without downloading' => 'Просматривать документы, изображения и видео можно прямо в браузере, не скачивая',
    'Mobile application development' => 'Разработка мобильных приложений',
    'We offer the creation of applications for iOS and Android in accordance with the technical task or vision of the customer. In consultation with our managers, it will become clear to you whether you need a mobile application and which one is specifically needed. By contacting us at an early stage, we will help you design a business model and a strategy for the phased development of the project. Analytics occupies an important place in our work: analysis of requirements and business processes, marketing and technical audit, requirements management at all stages of the project.' => 'Мы предлагаем создание приложений для iOS и Android в соответствии с техническим заданием или видением заказчика. При консультации с нашими менеджерами, Вам станет понятно, нужно ли Вам мобильное приложение и какое конкретно необходимо. Обращаясь к нам на ранней стадии, мы поможем Вам спроектировать бизнес-модель и стратегию поэтапного развития проекта. Важное место в нашей работе занимает аналитика: анализ требований и бизнес-процессов, маркетинговый и технический аудит, управление требованиями на всех этапах проекта.',
    'Business automation' => 'Автоматизация бизнеса',
    'Increase in profits' => 'Увеличение прибыли',
    'Company status' => 'Статус компании',
    'Modern smart watches are not limited to measuring the owner\'s pulse and the number of steps he has taken. These devices can act as a "virtual trainer" and help users keep fit without even going to the gym. Based on the data on physical activity, the application can recommend an individual training program. Also, modern watches help not only to monitor health, but also to monitor daily tasks, help with things like paying for purchases with built-in NFC and much more. Our team is ready to create any application for iOS and Android devices in order to expand the functionality of the watch and simplify the life of the owner' => 'Современные смарт-часы не ограничиваются тем, что измеряют пульс владельца и количество пройденных им шагов. Эти устройства могут выступать в роли «виртуального тренера» и помогать пользователям поддерживать себя в форме, даже не посещая спортзал. На основе данных о физической активности приложение может рекомендовать индивидуальную программу тренировок. Также совеременные часы помогают не только следить за здоровьем, но и следить за ежедневными задачами, помогают в таких вещах как оплата покупок со встроенным NFC и многое другое. Наша команда готова создать любое приложение под  устройства IOS и Android для того, чтобы расширить функционал часов и упростить жизнь владельцу',
    'Convenient receipt of notifications when syncing with your phone' => 'Удобное получение уведомлений при синхронизации с телефоном',
    'Autonomous health monitoring' => 'Автономный мониторинг состояния здоровья',
    'Control of the player, camera, voice recorder and other components' => 'Управление плеером, камерой, диктофоном и другими компонентами',
    'Using the API (programming interface) of large services, they can be integrated with any web resource, which leads to a significant expansion of the functionality and capabilities of the site. All this is aimed at simplifying the interaction between the site and its target audience, increasing the efficiency of business processes. We also offer other solutions to increase the profitability of your resource. To do this, contact us using the contact phone numbers or the online form.' => 'С помощью API (интерфейса программирования) крупных сервисов их можно интегрировать с любым веб-ресурсом, что приводит к значительному расширению функциональна и возможностей сайта. Все это направлено на упрощение взаимодействия между сайтом и его ЦА, повышения эффективности бизнес-процессов. Также мы предлогаем другие решения по повышению доходности вашего ресурса. Для этого свяжитесь с нами при помощи контактных телефонов или онлайн-формы.',
    'Optimization of work with the client base' => 'Оптимизация работы с клиентской базой',
    'Creating and managing mailing lists' => 'Создание списков рассылок и управление ими',
    'Overall increase in the efficiency of the resource' => 'Общее повышение эффективности работы ресурса',
    'Gateway Development' => 'Разработка шлюзов',
    'The API gateway is located between clients and services. It performs the function of a reverse proxy, passing requests from clients to services. It can also perform specialized tasks such as authentication, completion of SSL requests, and frequency limiting. If this gateway is not deployed, clients will have to send requests directly to external services. However, there may be some problems when providing clients with direct access to services.' => 'Шлюз API находится между клиентами и службами. Он выполняет функцию обратного прокси, передавая запросы от клиентов к службам. Он также может выполнять такие специализированные задачи, как аутентификация, завершение SSL-запросов и ограничение частоты. Если этот шлюз не будет развернут, клиенты должны будут отправлять запросы непосредственно к внешним службам. Но при предоставлении клиентам непосредственного доступа к службам могут возникнуть некоторые проблемы.',
    'Artificial intelligence is scientific knowledge and technology for creating intelligent machines, programs, services, applications, etc. AI gives technology the ability to perform functions that are considered the prerogative of a person.' => 'Искусственный интеллект – это научные знания и технология создания интеллектуальных машин, программ, сервисов, приложений и др. ИИ дает технике возможность выполнять функции, которые считаются прерогативой человека.',
    'The creation of artificial intelligence is designed to optimize the company\'s activities, open previously inaccessible horizons, reduce costs, create a competitive advantage and allow people to engage in creative activities rather than routine.' => 'Создание искусственного интеллекта призвано оптимизировать деятельность компании, открыть ранее недоступные горизонты, сократить расходы, создать конкурентное преимущество и дать людям заниматься творческой деятельностью, а не рутиной.',
    'Forecasting the behavior of competitors and the general situation on the market.' => 'Прогнозирование поведение конкурентов и общую ситуацию на рынке.',
    'Fast analytics of incoming data and instant response' => 'Быстрая  аналитика  поступающих данных и моментальное реагирование',
    'Creating algorithms to prevent financial losses' => 'Создание алгоритмов для предотвращения финансовых потерь',
    'Development of personalized Saas projects' => 'Разработка персонализированных Saas проектов',
    'The SaaS concept is a business model for using software, in which the customer is provided with a convenient WEB interface and full access to the application via the Internet. Thus, the newest business model of the relationship between the buyer and the software developer is presented. A distinctive feature of this type of software is the placement of the main "core" of the software part on the server of the software provider. Hence all the advantages of SaaS:' => 'SaaS концепция – бизнес-модель использования программного обеспечения, при котором заказчику предоставляется удобный WEB-интерфейс и полный доступ к приложению через интернет. Таким образом, представляется новейшая бизнес-модель взаимоотношений между покупателем и разработчиком ПО. Отличительная особенность программного обеспечения этого вида – размещение на сервере поставщика ПО основного «ядра» программной части. Отсюда следуют все преимущества SaaS:',
    'Flexible design for any database.' => 'Гибкое проектирование под любые базы данных.',
    'It is a reliable solution for data storage.' => 'Является надежным решением для хранения данных.',
    'Easy work with files that are stored on the server of the service owner' => 'Легкая работа с файлами, которые хранятся на сервере владельца сервиса',
    'Vice offers technical support services designed for the integrated solution of support and maintenance tasks, as well as the development of business IT infrastructure. A wide range of service support services, customer system maintenance experience and Visce resources provide customers with guarantees of effective support' => 'Visce предлагает услуги технической поддержки, предназначенные для комплексного решения задач поддержки и обслуживания, а также развития ИТ-инфраструктуры бизнеса. Широкий спектр услуг сервисной поддержки, опыт сопровождения систем клиентов и ресурсы Visce обеспечивают заказчикам гарантии эффективной поддержки',
    'The presence of its own contact center, which operates in 24x7 mode' => 'Наличие собственного контакт центра, который работает в режиме 24х7',
    'Guarantees of a high level of maintenance of information systems in accordance with the SLA service agreement' => 'Гарантии высокого уровня обслуживания информационных систем в соответствии с  соглашением  обслуживания SLA',
    'Minimizing business risks by reducing downtime and system failures' => 'Минимизация бизнес-рисков за счет сокращения времени простоя и сбоев системы',
    'Websites development' => 'Разработка сайтов',
    'Each of our Internet projects is a cost–effective working resource that makes a profit and fully justifies the costs invested in it. The virtual representation of your company is developed individually depending on the goals and objectives of the business. Our specialists carefully think over user scenarios, interface and offer optimal technical and design solutions.' => 'Каждый наш интернет-проект – это рентабельный рабочий ресурс, который приносит прибыль и полностью оправдывает затраты, вложенные в него. Виртуальное представительство вашей компании разрабатывается индивидуально в зависимости от целей и задач бизнеса. Наши специалисты тщательно продумывают пользовательские сценарии, интерфейс и предлагают оптимальные технические и дизайнерские решения.',
    'A website is a place where you can publish detailed information about a company' => 'Веб-сайт – это место, где можно опубликовать подробную информацию о компании',
    'this is a tool with which you can attract potential customers' => 'это инструмент, с помощью которого можно привлечь потенциальных клиентов',
    'The presence of a website indicates the technical advancement of the company and compliance with the requirements of the time' => 'Наличие веб-сайта свидетельствует о технической продвинутости компании и соответствии требованиям времени',
    'Smart Collection is a special CRM system designed to solve the problem of technological support of the operational process of departments working with distressed assets. The system is designed to optimize the work of the company\'s divisions.' => 'Smart Collection - специальная CRM система, разработанная с целью решения задачи технологического обеспечения операционного процесса подразделений, работающих с проблемными активами. Система призвана обеспечивать оптимизацию работы подразделений компании.',
    'The scalable software architecture makes it easy to expand the number of jobs and the number of concurrent users.' => 'Масштабируемая архитектура программного обеспечения позволяет легко расширить число рабочих мест и количество одновременно работающих пользователей.',
    'User access to the system is determined at the role level, while any active actions of operators in the system are recorded in the offline action log.' => 'Доступ пользователей к системе определяется на уровне ролей, при этом любые активные действия операторов в системе фиксируются в автономном журнале действий.',
    'The built-in back-office allows you to form work flows and provides prioritization.' => 'Встроенный back-office позволяет формировать потоки работы и обеспечивает расстановку приоритетов.',
    'Additional features of the system:' => 'Дополнительные возможности системы:',
    'Mobile application for the visiting group, with the ability to record video and photo reports, transfer online to the central platform "Smart Collection" Fixing the geolocation of collectors.' => 'Мобильное приложение для выездной группы, с возможностью фиксирования видео  и фото отчета, передачи онлайн в центральную платформу «Smart Collection» Фиксирование геолокации коллекторов.',
    'Leave your contact details and we will contact you soon to discuss cooperation.' => 'Оставьте свои контактные данные, и мы свяжемся с Вами в ближайшее время для того, чтобы обсудить сотрудничество',
    '<h1>What are Cookies?</h1>
<p>Cookies are small text files stored on your computer, tablet or mobile phone. They do NOT harm the computer or the security system and, contrary to erroneous opinion, have nothing to do with viruses such as Trojans. When you visit the site, cookies allow the site to "remember" you and your preferences to improve the quality of interaction with the site.</p>
<p>More information about cookies can be found on the Internet.</p><br>
<h2>How can I control the settings that allow the use of cookies?</h2>
<p>If you do not want to receive cookies, you can change your browser settings so that it notifies you when you receive these files, or completely refuse them. You can also delete already saved cookies.</p><br>
<h2>How we use cookies</h2>
<p>We use Google Analytics, a web analytics service provided by Google Inc. (Google). This service uses cookies to analyze the interaction with the site in order to improve the quality of service.</p>
<p>Our site uses the so-called user ID, which serves to identify customers in Google Analytics. Based on your behavior, Google creates a profile for your user ID. Google Analytics tracks the actions of anonymized users on different devices (tablets, PCs, smartphones, etc.).
Information about the use of websites collected by cookies (including IP address) is transmitted to Google and stored on servers located in the United States. Google uses the collected information to analyze user interaction with the website, compile reports on website traffic for us, as well as to provide other services related to the use of the website and the Internet. Google may transfer this information to third parties if required by law or for processing on behalf of Google. Your IP address is not linked to other data collected by Google.</p>
<p>Only the user ID is provided to Google, but not the information contained in the profile mentioned above, or other personal data. Summary data of the created profile is available to us. We do not add data that can be used for identification to the profile associated with the user ID.</p>
<p>You can opt out of tracking by user ID by sending an email to <a href="mailto:privacy@visce.ru ">privacy@visce.ru </a></p>
<p>You can also opt out of the use of cookies by setting the appropriate settings in your browser. Please note that in this case, some functions of the site may not be available. By using this website, you consent to the processing of your data by Google in the manner described above for the purposes listed in these rules.</p>
<p>More information about cookies can be found on the website <a href="https://www.aboutcookies.org " target="_blank">https://www.aboutcookies.org </a>.</p>
<p>* The displayed prices are valid at the time of the request and are based on contracts for a period of 2 years. Tariffs are subject to change depending on the selected products and services. Prices for office space and coworking are based on per person per month based on the availability of equipment. The Terms and Conditions apply.</p><br>
<h2>CONTRACT OF USE</h2>
<p>By continuing to use our site, you agree to the placement of cookies on your device. If you decide to opt out of our cookies, we cannot guarantee that your visit to the site will be as successful as when you receive cookies.</p>' => '<h1>Что такое файлы Cookie?</h1>
            <p>Файлы cookie — это текстовые файлы небольшого объема, сохраняемые на вашем компьютере, планшете или мобильном телефоне. Они НЕ вредят компьютеру или системе безопасности и, вопреки ошибочному мнению, не имеют ничего общего с такими вирусами, как троянские программы. При посещении сайта файлы cookie позволяют сайту «запоминать» вас и ваши предпочтения для повышения качества взаимодействия с сайтом.</p>
            <p>Более подробную информацию о файлах cookie можно найти в Интернете.</p><br>
            <h2>Как я могу контролировать настройки, позволяющие использование cookie?</h2>
            <p>Если вы не хотите получать файлы cookie, вы можете изменить настройки браузера так, чтобы он уведомлял вас о получении этих файлов, или же полностью отказаться от них. Вы также можете удалить уже сохраненные файлы cookie.</p><br>
            <h2>Как мы используем файлы cookie</h2>
            <p>Мы используем Google Analytics, сервис для веб-аналитики, предоставляемый Google Inc. (Google). Этот сервис использует файлы cookie для анализа взаимодействия с сайтом в целях повышения качества обслуживания.</p>
            <p>Наш сайт использует так называемый идентификатор пользователя, который служит для идентификации клиентов в Google Analytics. На основе вашего поведения Google создает профиль для вашего идентификатора пользователя. Google Analytics отслеживает действия анонимизированных пользователей на разных устройствах (планшеты, ПК, смартфоны и т.д.).
                Информация об использовании веб-сайтов, собранная с помощью файлов cookie (включая IP-адрес), передается Google и хранится на серверах, размещенных на территории США. Google использует собранные сведения для анализа взаимодействия пользователей с веб-сайтом, составления отчетов о посещаемости веб-сайта для нас, а также для оказания других услуг, связанных с использованием веб-сайта и сети Интернет. Google может передавать эти сведения третьим лицам, если это требуется по закону или для их обработки от лица Google. Ваш IP-адрес не связан с другими данными, собранными Google.</p>
            <p>В распоряжение Google предоставляется только идентификатор пользователя, но не информация, содержащаяся в упомянутом выше профиле, или другие персональные данные. Нам доступны сводные данные созданного профиля. Мы не добавляем данные, которые можно использовать для установления личности, в профиль, связанный с идентификатором пользователя.</p>
            <p>Вы можете отказаться от отслеживания по идентификатору пользователя, отправив письмо по адресу <a href="mailto:privacy@visce.ru">privacy@visce.ru</a></p>
            <p>Вы также можете отказаться от использования файлов cookie, установив соответствующие настройки в браузере. Обратите внимание на то, что в этом случае некоторые функции сайта могут быть недоступны. Пользуясь этим сайтом, вы даете свое согласие на обработку своих данных компанией Google описанным выше образом в целях, перечисленных в этих правилах.</p>
            <p>Более подробную информацию о файлах cookie можно найти на сайте <a href="https://www.aboutcookies.org" target="_blank">https://www.aboutcookies.org</a>.</p>
            <p>* Отображаемые цены действительны на момент запроса и основаны на договорах сроком на 2 года. Тарифы подлежат изменению в зависимости от выбранных продуктов и услуг. Цены на офисные помещения и коворкинг приведены из расчета на человека в месяц на основании доступности оборудования. Применяются Условия и положения.</p><br>
            <h2>ДОГОВОР ПОЛЬЗОВАНИЯ</h2>
            <p>Продолжая пользоваться нашим сайтом, вы соглашаетесь на размещение файлов cookie на вашем устройстве. Если вы решили отказаться от наших файлов cookie, мы не можем гарантировать, что ваше посещение сайта будет таким же успешным, как при получении файлов cookie.</p>',
    '<h1>Personal Data Processing Policy</h1>
<h2>1. General provisions</h2>
<p>This Personal data processing policy is compiled in accordance with the requirements of Federal Law No. 152-FZ of 27.07.2006 "On Personal Data" (hereinafter referred to as the Personal Data Law) and defines the procedure for processing personal data and measures to ensure the security of personal data taken by VISCE GROUP LLC (hereinafter referred to as the Operator).</p>
1.1. The Operator sets as its most important goal and condition for the implementation of its activities the observance of the rights and freedoms of man and citizen in the processing of his personal data, including the protection of the rights to privacy, personal and family secrets.</p>
<p>1.2. This Operator\'s policy regarding the processing of personal data (hereinafter referred to as the Policy) applies to all information that the Operator can receive about website visitors https://visce.ru /.</p><br>
<h2>2. Basic concepts used in the Policy</h2>
<p>2.1. Automated processing of personal data – processing of personal data using computer technology.</p>
<p>2.2. Blocking of personal data – temporary termination of the processing of personal data (except in cases where processing is necessary to clarify personal data).</p>
<p>2.3. Website - a set of graphic and informational materials, as well as computer programs and databases that ensure their availability on the Internet at a network address https://visce.ru /.</p>
<p>2.4. Personal data information system — a set of personal data contained in databases, and information technologies and technical means that ensure their processing.</p>
<p>2.5. Depersonalization of personal data — actions as a result of which it is impossible to determine, without the use of additional information, the ownership of personal data to a specific User or other subject of personal data.</p>
2.6. Processing of personal data – any action (operation) or a set of actions (operations) performed with or without the use of automation tools with personal data, including collection, recording, systematization, accumulation, storage, clarification (updating, modification), extraction, use, transfer (distribution, provision, access), depersonalization, blocking, deletion, destruction of personal data.</p>
2.7. Operator – a state body, municipal body, legal entity or individual, independently or jointly with other persons organizing and (or) processing personal data, as well as determining the purposes of processing personal data, the composition of personal data to be processed, actions (operations) performed with personal data.</p>
<p>2.8. Personal data – any information related directly or indirectly to a specific or identifiable User of the Website https://visce.ru /.</p>
2.9. Personal data authorized by the subject of personal data for distribution - personal data to which an unlimited number of persons have access by the subject of personal data by giving consent to the processing of personal data authorized by the subject of personal data for distribution in accordance with the procedure provided for by the Law on Personal Data (hereinafter - personal data authorized for distribution).</p>
<p>2.10. User – any visitor to the website https://visce.ru /.</p>
2.11. Provision of personal data – actions aimed at disclosure of personal data to a certain person or a certain circle of persons.</p>
2.12. Dissemination of personal data – any actions aimed at disclosure of personal data to an indefinite circle of persons (transfer of personal data) or familiarization with personal data of an unlimited circle of persons, including the publication of personal data in the media, placement in information and telecommunications networks or providing access to personal data to anyor in another way.</p>
2.13. Cross–border transfer of personal data is the transfer of personal data to the territory of a foreign state to the authority of a foreign state, a foreign individual or a foreign legal entity.
2.14. Destruction of personal data – any actions as a result of which personal data is permanently destroyed with the impossibility of further restoration of the content of personal data in the personal data information system and (or) the material carriers of personal data are destroyed.</p><br>
<h2>3. Basic rights and obligations of the Operator</h2>
<p>3.1. The Operator has the right to:<br>
– receive reliable information and/or documents containing personal data from the subject of personal data;<br>
– if the subject of personal data withdraws consent to the processing of personal data, the Operator has the right to continue processing personal data without the consent of the subject of personal data if there are grounds specified in the Law on Personal Data;<br>
– independently determine the composition and list of measures necessary and sufficient to ensure the fulfillment of obligations provided for by the Law on Personal Data and regulatory legal acts adopted in accordance with it, unless otherwise provided by the Law on Personal Data or other federal laws.</p>
<p>3.2. The operator is obliged to:<br>
– to provide the subject of personal data, at his request, with information concerning the processing of his personal data;<br>
– organize the processing of personal data in accordance with the procedure established by the current legislation of the Russian Federation;<br>
– respond to the requests and requests of personal data subjects and their legal representatives in accordance with the requirements of the Law on Personal Data;<br>
– to report to the authorized body for the protection of the rights of personal data subjects at the request of this body the necessary information within 30 days from the date of receipt of such a request;<br>
– publish or otherwise provide unrestricted access to this Policy regarding the processing of personal data;<br>
– take legal, organizational and technical measures to protect personal data from unauthorized or accidental access to them, destruction, modification, blocking, copying, provision, dissemination of personal data, as well as from other illegal actions with respect to personal data;<br>
– stop the transfer (distribution, provision, access) of personal data, stop processing and destroy personal data in the manner and cases provided for by the Law on Personal Data;<br>
– perform other duties stipulated by the Law on Personal Data.</p><br>
<h2>4. Basic rights and obligations of personal data subjects</h2>
<p>4.1. Personal data subjects have the right to:<br>
– receive information concerning the processing of his personal data, except in cases provided for by federal laws. The information is provided to the personal data subject by the Operator in an accessible form, and it should not contain personal data related to other personal data subjects, except in cases where there are legitimate grounds for disclosure of such personal data. The list of information and the procedure for obtaining it is established by the Law on Personal Data;<br>
– require the operator to clarify his personal data, block or destroy them if the personal data is incomplete, outdated, inaccurate, illegally obtained or not necessary for the stated purpose of processing, as well as take measures provided by law to protect their rights;<br>
– to put forward a condition of prior consent when processing personal data in order to promote goods, works and services on the market;<br>
– to revoke consent to the processing of personal data;<br>
– appeal to the authorized body for the protection of the rights of personal data subjects or in court against the illegal actions or inaction of the Operator when processing his personal data;<br>
– to exercise other rights provided for by the legislation of the Russian Federation.</p>
<p>4.2. The subjects of personal data are obliged to:<br>
– provide the Operator with reliable data about yourself;<br>
– inform the Operator about the clarification (updating, modification) of their personal data.</p>
<p>4.3. Persons who have provided the Operator with false information about themselves or information about another personal data subject without the latters consent are liable in accordance with the legislation of the Russian Federation.</p><br>
<h2>5. The Operator may process the following personal data of the User</h2>
<p>5.1. Surname, first name, patronymic.</p>
<p>5.2. Email address.</p>
<p>5.3. Phone numbers.</p>
<p>5.4. Also on site is the collection and processing of anonymous data about visitors (including cookies) using Internet statistics (Yandex Metric and Google Analytics and others).</p>
<p>5.5. The above data, hereinafter referred to in the text of the Policy, are combined by the general concept of Personal Data.</p>
<p>5.6. Processing of special categories of personal data concerning race, nationality, political views, religious or philosophical beliefs, intimate life, is not carried out by the Operator.</p>
<p>5.7. Processing of personal data permitted for distribution from among the special categories of personal data specified in Part 1 of Article 10 of the Law on Personal Data is allowed if the prohibitions and conditions provided for in Article 10.1 of the Law on Personal Data are observed.</p>
' => '<h1>Политика в отношении обработки персональных данных</h1>
			<h2>1. Общие положения</h2>
			<p>Настоящая политика обработки персональных данных составлена в соответствии с требованиями Федерального закона от 27.07.2006. №152-ФЗ «О персональных данных» (далее - Закон о персональных данных) и определяет порядок обработки персональных данных и меры по обеспечению безопасности персональных данных, предпринимаемые ООО "ВИСЦЕ ГРУПП" (далее – Оператор).</p>
			<p>1.1. Оператор ставит своей важнейшей целью и условием осуществления своей деятельности соблюдение прав и свобод человека и гражданина при обработке его персональных данных, в том числе защиты прав на неприкосновенность частной жизни, личную и семейную тайну.</p>
			<p>1.2. Настоящая политика Оператора в отношении обработки персональных данных (далее – Политика) применяется ко всей информации, которую Оператор может получить о посетителях веб-сайта https://visce.ru/.</p><br>
			<h2>2. Основные понятия, используемые в Политике</h2>
			<p>2.1. Автоматизированная обработка персональных данных – обработка персональных данных с помощью средств вычислительной техники.</p>
			<p>2.2. Блокирование персональных данных – временное прекращение обработки персональных данных (за исключением случаев, если обработка необходима для уточнения персональных данных).</p>
			<p>2.3. Веб-сайт – совокупность графических и информационных материалов, а также программ для ЭВМ и баз данных, обеспечивающих их доступность в сети интернет по сетевому адресу https://visce.ru/.</p>
			<p>2.4. Информационная система персональных данных — совокупность содержащихся в базах данных персональных данных, и обеспечивающих их обработку информационных технологий и технических средств.</p>
			<p>2.5. Обезличивание персональных данных — действия, в результате которых невозможно определить без использования дополнительной информации принадлежность персональных данных конкретному Пользователю или иному субъекту персональных данных.</p>
			<p>2.6. Обработка персональных данных – любое действие (операция) или совокупность действий (операций), совершаемых с использованием средств автоматизации или без использования таких средств с персональными данными, включая сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление, уничтожение персональных данных.</p>
			<p>2.7. Оператор – государственный орган, муниципальный орган, юридическое или физическое лицо, самостоятельно или совместно с другими лицами организующие и (или) осуществляющие обработку персональных данных, а также определяющие цели обработки персональных данных, состав персональных данных, подлежащих обработке, действия (операции), совершаемые с персональными данными.</p>
			<p>2.8. Персональные данные – любая информация, относящаяся прямо или косвенно к определенному или определяемому Пользователю веб-сайта https://visce.ru/.</p>
			<p>2.9. Персональные данные, разрешенные субъектом персональных данных для распространения, - персональные данные, доступ неограниченного круга лиц к которым предоставлен субъектом персональных данных путем дачи согласия на обработку персональных данных, разрешенных субъектом персональных данных для распространения в порядке, предусмотренном Законом о персональных данных (далее - персональные данные, разрешенные для распространения).</p>
			<p>2.10. Пользователь – любой посетитель веб-сайта https://visce.ru/.</p>
			<p>2.11. Предоставление персональных данных – действия, направленные на раскрытие персональных данных определенному лицу или определенному кругу лиц.</p>
			<p>2.12. Распространение персональных данных – любые действия, направленные на раскрытие персональных данных неопределенному кругу лиц (передача персональных данных) или на ознакомление с персональными данными неограниченного круга лиц, в том числе обнародование персональных данных в средствах массовой информации, размещение в информационно-телекоммуникационных сетях или предоставление доступа к персональным данным каким-либо иным способом.</p>
			<p>2.13. Трансграничная передача персональных данных – передача персональных данных на территорию иностранного государства органу власти иностранного государства, иностранному физическому или иностранному юридическому лицу.</p>
			<p>2.14. Уничтожение персональных данных – любые действия, в результате которых персональные данные уничтожаются безвозвратно с невозможностью дальнейшего восстановления содержания персональных данных в информационной системе персональных данных и (или) уничтожаются материальные носители персональных данных.</p><br>
			<h2>3. Основные права и обязанности Оператора</h2>
			<p>3.1. Оператор имеет право:<br>
			– получать от субъекта персональных данных достоверные информацию и/или документы, содержащие персональные данные;<br>
			– в случае отзыва субъектом персональных данных согласия на обработку персональных данных Оператор вправе продолжить обработку персональных данных без согласия субъекта персональных данных при наличии оснований, указанных в Законе о персональных данных;<br>
			– самостоятельно определять состав и перечень мер, необходимых и достаточных для обеспечения выполнения обязанностей, предусмотренных Законом о персональных данных и принятыми в соответствии с ним нормативными правовыми актами, если иное не предусмотрено Законом о персональных данных или другими федеральными законами.</p>
			<p>3.2. Оператор обязан:<br>
			– предоставлять субъекту персональных данных по его просьбе информацию, касающуюся обработки его персональных данных;<br>
			– организовывать обработку персональных данных в порядке, установленном действующим законодательством РФ;<br>
			– отвечать на обращения и запросы субъектов персональных данных и их законных представителей в соответствии с требованиями Закона о персональных данных;<br>
			– сообщать в уполномоченный орган по защите прав субъектов персональных данных по запросу этого органа необходимую информацию в течение 30 дней с даты получения такого запроса;<br>
			– публиковать или иным образом обеспечивать неограниченный доступ к настоящей Политике в отношении обработки персональных данных;<br>
			– принимать правовые, организационные и технические меры для защиты персональных данных от неправомерного или случайного доступа к ним, уничтожения, изменения, блокирования, копирования, предоставления, распространения персональных данных, а также от иных неправомерных действий в отношении персональных данных;<br>
			– прекратить передачу (распространение, предоставление, доступ) персональных данных, прекратить обработку и уничтожить персональные данные в порядке и случаях, предусмотренных Законом о персональных данных;<br>
			– исполнять иные обязанности, предусмотренные Законом о персональных данных.</p><br>
			<h2>4. Основные права и обязанности субъектов персональных данных</h2>
			<p>4.1. Субъекты персональных данных имеют право:<br>
			– получать информацию, касающуюся обработки его персональных данных, за исключением случаев, предусмотренных федеральными законами. Сведения предоставляются субъекту персональных данных Оператором в доступной форме, и в них не должны содержаться персональные данные, относящиеся к другим субъектам персональных данных, за исключением случаев, когда имеются законные основания для раскрытия таких персональных данных. Перечень информации и порядок ее получения установлен Законом о персональных данных;<br>
			– требовать от оператора уточнения его персональных данных, их блокирования или уничтожения в случае, если персональные данные являются неполными, устаревшими, неточными, незаконно полученными или не являются необходимыми для заявленной цели обработки, а также принимать предусмотренные законом меры по защите своих прав;<br>
			– выдвигать условие предварительного согласия при обработке персональных данных в целях продвижения на рынке товаров, работ и услуг;<br>
			– на отзыв согласия на обработку персональных данных;<br>
			– обжаловать в уполномоченный орган по защите прав субъектов персональных данных или в судебном порядке неправомерные действия или бездействие Оператора при обработке его персональных данных;<br>
			– на осуществление иных прав, предусмотренных законодательством РФ.</p>
			<p>4.2. Субъекты персональных данных обязаны:<br>
			– предоставлять Оператору достоверные данные о себе;<br>
			– сообщать Оператору об уточнении (обновлении, изменении) своих персональных данных.</p>
			<p>4.3. Лица, передавшие Оператору недостоверные сведения о себе, либо сведения о другом субъекте персональных данных без согласия последнего, несут ответственность в соответствии с законодательством РФ.</p><br>
			<h2>5. Оператор может обрабатывать следующие персональные данные Пользователя</h2>
			<p>5.1. Фамилия, имя, отчество.</p>
			<p>5.2. Электронный адрес.</p>
			<p>5.3. Номера телефонов.</p>
			<p>5.4. Также на сайте происходит сбор и обработка обезличенных данных о посетителях (в т.ч. файлов «cookie») с помощью сервисов интернет-статистики (Яндекс Метрика и Гугл Аналитика и других).</p>
			<p>5.5. Вышеперечисленные данные далее по тексту Политики объединены общим понятием Персональные данные.</p>
			<p>5.6. Обработка специальных категорий персональных данных, касающихся расовой, национальной принадлежности, политических взглядов, религиозных или философских убеждений, интимной жизни, Оператором не осуществляется.</p>
			<p>5.7. Обработка персональных данных, разрешенных для распространения, из числа специальных категорий персональных данных, указанных в ч. 1 ст. 10 Закона о персональных данных, допускается, если соблюдаются запреты и условия, предусмотренные ст. 10.1 Закона о персональных данных.</p>
			<p>5.8. Согласие Пользователя на обработку персональных данных, разрешенных для распространения, оформляется отдельно от других согласий на обработку его персональных данных. При этом соблюдаются условия, предусмотренные, в частности, ст. 10.1 Закона о персональных данных. Требования к содержанию такого согласия устанавливаются уполномоченным органом по защите прав субъектов персональных данных.</p>
			<p>&nbsp;5.8.1 Согласие на обработку персональных данных, разрешенных для распространения, Пользователь предоставляет Оператору непосредственно.</p>
			<p>&nbsp;5.8.2 Оператор обязан в срок не позднее трех рабочих дней с момента получения указанного согласия Пользователя опубликовать информацию об условиях обработки, о наличии запретов и условий на обработку неограниченным кругом лиц персональных данных, разрешенных для распространения.</p>
			<p>&nbsp;5.8.3 Передача (распространение, предоставление, доступ) персональных данных, разрешенных субъектом персональных данных для распространения, должна быть прекращена в любое время по требованию субъекта персональных данных. Данное требование должно включать в себя фамилию, имя, отчество (при наличии), контактную информацию (номер телефона, адрес электронной почты или почтовый адрес) субъекта персональных данных, а также перечень персональных данных, обработка которых подлежит прекращению. Указанные в данном требовании персональные данные могут обрабатываться только Оператором, которому оно направлено.</p>
			<p>&nbsp;5.8.4 Согласие на обработку персональных данных, разрешенных для распространения, прекращает свое действие с момента поступления Оператору требования, указанного в п. 5.8.3 настоящей Политики в отношении обработки персональных данных.</p><br>
			<h2>6. Принципы обработки персональных данных</h2>
			<p>6.1. Обработка персональных данных осуществляется на законной и справедливой основе.</p>
			<p>6.2. Обработка персональных данных ограничивается достижением конкретных, заранее определенных и законных целей. Не допускается обработка персональных данных, несовместимая с целями сбора персональных данных.</p>
			<p>6.3. Не допускается объединение баз данных, содержащих персональные данные, обработка которых осуществляется в целях, несовместимых между собой.</p>
			<p>6.4. Обработке подлежат только персональные данные, которые отвечают целям их обработки.</p>
			<p>6.5. Содержание и объем обрабатываемых персональных данных соответствуют заявленным целям обработки. Не допускается избыточность обрабатываемых персональных данных по отношению к заявленным целям их обработки.</p>
			<p>6.6. При обработке персональных данных обеспечивается точность персональных данных, их достаточность, а в необходимых случаях и актуальность по отношению к целям обработки персональных данных. Оператор принимает необходимые меры и/или обеспечивает их принятие по удалению или уточнению неполных или неточных данных.</p>
			<p>6.7. Хранение персональных данных осуществляется в форме, позволяющей определить субъекта персональных данных, не дольше, чем этого требуют цели обработки персональных данных, если срок хранения персональных данных не установлен федеральным законом, договором, стороной которого, выгодоприобретателем или поручителем по которому является субъект персональных данных. Обрабатываемые персональные данные уничтожаются либо обезличиваются по достижении целей обработки или в случае утраты необходимости в достижении этих целей, если иное не предусмотрено федеральным законом.</p><br>
			<h2>7. Цели обработки персональных данных</h2>
			<p>7.1. Цель обработки персональных данных Пользователя:<br>
			– информирование Пользователя посредством отправки электронных писем;<br>
			– заключение, исполнение и прекращение гражданско-правовых договоров;<br>
			– предоставление доступа Пользователю к сервисам, информации и/или материалам, содержащимся на веб-сайте https://visce.ru/.</p>
			<p>7.2. Также Оператор имеет право направлять Пользователю уведомления о новых продуктах и услугах, специальных предложениях и различных событиях. Пользователь всегда может отказаться от получения информационных сообщений, направив Оператору письмо на адрес электронной почты privacy@visce.ru с пометкой «Отказ от уведомлений о новых продуктах и услугах и специальных предложениях».</p>
			<p>7.3. Обезличенные данные Пользователей, собираемые с помощью сервисов интернет-статистики, служат для сбора информации о действиях Пользователей на сайте, улучшения качества сайта и его содержания.</p><br>
			<h2>8. Правовые основания обработки персональных данных</h2>
			<p>8.1. Правовыми основаниями обработки персональных данных Оператором являются:<br>
			– договоры, заключаемые между оператором и субъектом персональных данных;<br>
			– федеральные законы, иные нормативно-правовые акты в сфере защиты персональных данных;<br>
			– согласия Пользователей на обработку их персональных данных, на обработку персональных данных, разрешенных для распространения.</p>
			<p>8.2. Оператор обрабатывает персональные данные Пользователя только в случае их заполнения и/или отправки Пользователем самостоятельно через специальные формы, расположенные на сайте https://visce.ru/ или направленные Оператору посредством электронной почты. Заполняя соответствующие формы и/или отправляя свои персональные данные Оператору, Пользователь выражает свое согласие с данной Политикой.</p>
			<p>8.3. Оператор обрабатывает обезличенные данные о Пользователе в случае, если это разрешено в настройках браузера Пользователя (включено сохранение файлов «cookie» и использование технологии JavaScript).</p>
			<p>8.4. Субъект персональных данных самостоятельно принимает решение о предоставлении его персональных данных и дает согласие свободно, своей волей и в своем интересе.</p><br>
			<h2>9. Условия обработки персональных данных</h2>
			<p>9.1. Обработка персональных данных осуществляется с согласия субъекта персональных данных на обработку его персональных данных.</p>
			<p>9.2. Обработка персональных данных необходима для достижения целей, предусмотренных международным договором Российской Федерации или законом, для осуществления возложенных законодательством Российской Федерации на оператора функций, полномочий и обязанностей.</p>
			<p>9.3. Обработка персональных данных необходима для осуществления правосудия, исполнения судебного акта, акта другого органа или должностного лица, подлежащих исполнению в соответствии с законодательством Российской Федерации об исполнительном производстве.</p>
			<p>9.4. Обработка персональных данных необходима для исполнения договора, стороной которого либо выгодоприобретателем или поручителем по которому является субъект персональных данных, а также для заключения договора по инициативе субъекта персональных данных или договора, по которому субъект персональных данных будет являться выгодоприобретателем или поручителем.</p>
			<p>9.5. Обработка персональных данных необходима для осуществления прав и законных интересов оператора или третьих лиц либо для достижения общественно значимых целей при условии, что при этом не нарушаются права и свободы субъекта персональных данных.</p>
			<p>9.6. Осуществляется обработка персональных данных, доступ неограниченного круга лиц к которым предоставлен субъектом персональных данных либо по его просьбе (далее – общедоступные персональные данные).</p>
			<p>9.7. Осуществляется обработка персональных данных, подлежащих опубликованию или обязательному раскрытию в соответствии с федеральным законом.</p><br>
			<h2>10. Порядок сбора, хранения, передачи и других видов обработки персональных данных</h2>
			<p>Безопасность персональных данных, которые обрабатываются Оператором, обеспечивается путем реализации правовых, организационных и технических мер, необходимых для выполнения в полном объеме требований действующего законодательства в области защиты персональных данных.</p>
			<p>10.1. Оператор обеспечивает сохранность персональных данных и принимает все возможные меры, исключающие доступ к персональным данным неуполномоченных лиц.
			<p>10.2. Персональные данные Пользователя никогда, ни при каких условиях не будут переданы третьим лицам, за исключением случаев, связанных с исполнением действующего законодательства либо в случае, если субъектом персональных данных дано согласие Оператору на передачу данных третьему лицу для исполнения обязательств по гражданско-правовому договору.</p>
			<p>10.3. В случае выявления неточностей в персональных данных, Пользователь может актуализировать их самостоятельно, путем направления Оператору уведомление на адрес электронной почты Оператора privacy@visce.ru с пометкой «Актуализация персональных данных».</p>
			<p>10.4. Срок обработки персональных данных определяется достижением целей, для которых были собраны персональные данные, если иной срок не предусмотрен договором или действующим законодательством.
			Пользователь может в любой момент отозвать свое согласие на обработку персональных данных, направив Оператору уведомление посредством электронной почты на электронный адрес Оператора privacy@visce.ru с пометкой «Отзыв согласия на обработку персональных данных».</p>
			<p>10.5. Вся информация, которая собирается сторонними сервисами, в том числе платежными системами, средствами связи и другими поставщиками услуг, хранится и обрабатывается указанными лицами (Операторами) в соответствии с их Пользовательским соглашением и Политикой конфиденциальности. Субъект персональных данных и/или Пользователь обязан самостоятельно своевременно ознакомиться с указанными документами. Оператор не несет ответственность за действия третьих лиц, в том числе указанных в настоящем пункте поставщиков услуг.</p>
			<p>10.6. Установленные субъектом персональных данных запреты на передачу (кроме предоставления доступа), а также на обработку или условия обработки (кроме получения доступа) персональных данных, разрешенных для распространения, не действуют в случаях обработки персональных данных в государственных, общественных и иных публичных интересах, определенных законодательством РФ.</p>
			<p>10.7. Оператор при обработке персональных данных обеспечивает конфиденциальность персональных данных.</p>
			<p>10.8. Оператор осуществляет хранение персональных данных в форме, позволяющей определить субъекта персональных данных, не дольше, чем этого требуют цели обработки персональных данных, если срок хранения персональных данных не установлен федеральным законом, договором, стороной которого, выгодоприобретателем или поручителем по которому является субъект персональных данных.</p>
			<p>10.9. Условием прекращения обработки персональных данных может являться достижение целей обработки персональных данных, истечение срока действия согласия субъекта персональных данных или отзыв согласия субъектом персональных данных, а также выявление неправомерной обработки персональных данных.</p><br>
			<h2>11. Перечень действий, производимых Оператором с полученными персональными данными</h2>
			<p>11.1. Оператор осуществляет сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление и уничтожение персональных данных.</p>
			<p>11.2. Оператор осуществляет автоматизированную обработку персональных данных с получением и/или передачей полученной информации по информационно-телекоммуникационным сетям или без таковой.</p><br>
			<h2>12. Трансграничная передача персональных данных</h2>
			<p>12.1. Оператор до начала осуществления трансграничной передачи персональных данных обязан убедиться в том, что иностранным государством, на территорию которого предполагается осуществлять передачу персональных данных, обеспечивается надежная защита прав субъектов персональных данных.</p>
			<p>12.2. Трансграничная передача персональных данных на территории иностранных государств, не отвечающих вышеуказанным требованиям, может осуществляться только в случае наличия согласия в письменной форме субъекта персональных данных на трансграничную передачу его персональных данных и/или исполнения договора, стороной которого является субъект персональных данных.</p><br>
			<h2>13. Конфиденциальность персональных данных</h2>
			<p>Оператор и иные лица, получившие доступ к персональным данным, обязаны не раскрывать третьим лицам и не распространять персональные данные без согласия субъекта персональных данных, если иное не предусмотрено федеральным законом.</p><br>
			<h2>14. Заключительные положения</h2>
			<p>14.1. Пользователь может получить любые разъяснения по интересующим вопросам, касающимся обработки его персональных данных, обратившись к Оператору с помощью электронной почты <a href="mailto:privacy@visce.ru">privacy@visce.ru</a></p>
			<p>14.2. В данном документе будут отражены любые изменения политики обработки персональных данных Оператором. Политика действует бессрочно до замены ее новой версией./p>
			<p>14.3. Актуальная версия Политики в свободном доступе расположена в сети Интернет по адресу <a href="https://visce.ru/privacy">https://visce.ru/privacy</a></p>',
    'Stages of project development' => 'Этапы разработки проекта',
    'Project idea' => 'Идея проекта',
    'Our team together with the customer is working on the idea of the project based on his wishes and requirements. At this stage, the client\'s wishes for the type of project, its structure and design are identified, adjustments are made to the overall concept.' => 'Наша команда совместно с заказчиком прорабатывает идею проекта на основании его желаний и требований. На этом этапе выявляются пожелания клиента к типу проекта, его структуре и дизайну, вносятся коррективы в общую концепцию.',
    'Analytics' => 'Аналитика',
    'At this stage, the customer and our team determine the goals to be achieved during development, fix business tasks, user requirements, and so on. This process takes place in the format of a dialogue, the participation of both sides is important here.  The analyst\'s task is to foresee all possible risks and offer options for optimizing the development process. The more details the customer will announce, the more accurately the terms of reference will be drawn up and, accordingly, the better the final result will be.' => 'На этом этапе заказчик и наша команда определяют цели, которые предстоит достичь в ходе разработки, фиксируют бизнес-задачи, пользовательские требования и прочее. Этот процесс происходит в формате диалога, здесь важно участие обеих сторон.  Задача аналитика заключается в том, чтобы предусмотреть все возможные риски и предложить варианты оптимизации процесса разработки. Чем больше деталей озвучит заказчик, тем точнее будет составлено техническое задание и, соответственно, тем качественнее будет финальный результат.',
    'Project evaluation' => 'Оценка проекта',
    'The collected data is analyzed, and a product model is created based on it, which is equally understandable to both the customer and the developer. Next, the preliminary time and production costs necessary to create a product are calculated. The best option is a presentation that describes in detail the evaluation of the project, possible risks, the team to work on the project, various options for the implementation of tasks, conditions, stages and other details.' => 'Собранные данные анализируются, и на их основе создается модель продукта, которая одинаково понятна как заказчику, так и разработчику. Далее рассчитываются предварительные временные и производительные затраты, необходимые для создания продукта. Оптимальный вариант – презентация, в которой подробно описана оценка проекта, возможные риски, команда для работы над проектом, различные варианты реализации задач, условия, этапность и другие детали.',
    'When all the issues of the preliminary assessment are settled, the design stage begins, including:' => 'Когда все вопросы по предварительной оценке улажены, наступает этап проектирования, включающий:',
    'Development of a project map with reference points for reconciliation of results' => 'Разработка карты проекта с указанием опорных точек для сверки результатов',
    'Architecture design' => 'Проектирование архитектуры',
    'Choosing a technology stack – development tools that include programming languages, frameworks, database management systems, compilers, etc.' => 'Выбор технологического стека – инструментов разработки, которые включают языки программирования, фреймворки, системы управления базами данных, компиляторы и т. д.',
    'Design' => 'Дизайн',
    'After the analysis is completed, the project is evaluated and agreed, the developers can proceed to the design. This stage includes two blocks:
<ul>
<li>Development of UX – user interface design. UX is responsible for the logic of building system elements, adaptability and usability of the product. </li>
<li>UI development – rendering of interface elements: blocks, buttons, icons that are assembled into a ready-made layout.</li>
</ul>
Many people mistakenly believe that design is only about the visual part. In fact, design is responsible for shaping the user experience.' => 'После того как завершена аналитика, проект оценен и согласован, разработчики могут переходить к дизайну. Этот этап включает два блока:
	      	   	   		  	<ul>
	      	   	   		  		<li>Разработку UX – дизайн пользовательского интерфейса. UX отвечает за логику построения элементов системы, адаптивность и юзабилити продукта. </li>
	      	   	   		  		<li>Разработку UI – отрисовку элементов интерфейса: блоки, кнопки, иконки, которые собираются в готовый макет.</li>
	      	   	   		  	</ul>
	      	   	   		  	Многие ошибочно полагают, что дизайн – это только о визуальной части. На самом деле дизайн отвечает за формирование пользовательского опыта.',
    'This stage implies the implementation of the customer\'s ideas already formulated in practical steps. The ideal format is development by sprints. The Visce team, in accordance with the project map, carries out the work and shows the customer the result of each part. Development in the sprint format is convenient and effective, because it allows you to collect feedback as quickly as possible, respond to changes and make edits. This approach is based on a flexible methodology and is called iterative.' => 'Этот этап подразумевает реализацию идей заказчика уже оформленных в практические шаги. Идеальный формат – разработка спринтами. Команда Visce в соответствии с картой проекта проводит работу и показывает заказчику результат каждой части. Разработка в формате спринтов удобна и эффективна, т.к. позволяет максимально быстро собирать обратную связь, реагировать на изменения и вносить правки. Такой подход строится на основе гибкой методологии и называется итеративным.',
    'Testing' => 'Тестирование',
    'Testing of a software product is one of the most important stages in the process of its development, because before the presentation of a new product to consumers, the company must be fully confident in its operability. Therefore, it is so important to identify critical bugs in time, check the functionality of the product, conduct a full analysis and implement recommendations for improvement.
To do this, QA engineers can use various methods and methods of testing a new IT product: modular, integration, functional, acceptance.' => 'Тестирование программного продукта – один из важнейших этапов в процессе его разработки, ведь до презентации нового продукта потребителям компания должна быть полностью уверена в его работоспособности. Поэтому так важно вовремя выявить критические баги, проверить функционал продукта, провести полноценный анализ и реализовать рекомендации по улучшению.
							Для этого QA-инженеры могут использовать различные способы и методы тестирования нового IT-продукта: модульные, интеграционные, функциональные, приемочные.',
    'Launch' => 'Запуск',
    'After the testing is done and the bugs are fixed, the finished product will be launched. If earlier the product was available only to a narrow circle of developers and quality control specialists, now we have to meet with real users. At this stage, monitoring tools are also configured to help study user behavior and refine the product, if necessary.' => 'После того, как тестирование проведено и баги устранены, предстоит запуск готового продукта. Если раньше продукт был доступен только узкому кругу разработчиков и специалистов по контролю качества, то теперь предстоит встреча с реальными пользователями. На этом этапе также настраиваются инструменты мониторинга, помогающие изучить поведение пользователей и доработать продукт, если потребуется.',
    'Transfer of rights' => 'Передача прав',
    'The launch has been made – the developers have done their part and are handing over the finished product to the owner. At this stage, control over the software and documentation is completely transferred to the customer. Detailed conditions for the transfer of rights are prescribed in the cooperation agreement between the customer and the developer company.' => 'Запуск произведен – разработчики выполнили свою часть работы и передают готовый продукт владельцу. На этом этапе контроль над программной частью и документацией полностью переходит заказчику. Детальные условия передачи прав прописываются в договоре о сотрудничестве между заказчиком и компанией-разработчиком.',
    'After completion of the work, the product needs further technical support. At this stage, the developer offers temporary or permanent support in order to reduce the risks of failures after the launch of the new system and ensure quick recovery in case of malfunctions. Temporary maintenance involves the elimination of possible defects for a limited period. Constant technical support is convenient if you need to regularly receive the latest software updates. In this case, possible failures should be eliminated quickly and unnoticeably for users.' => 'После завершения работ продукт нуждается в дальнейшей техподдержке. На этом этапе разработчик предлагает временное или постоянное сопровождение, чтобы после запуска новой системы снизить риски сбоев и обеспечить быстрое восстановление в случае неполадок. Временное обслуживание предполагает устранение возможных недочетов в течение ограниченного периода. Постоянная техподдержка удобна, если необходимо регулярно получать последние обновления ПО. В этом случае возможные сбои должны ликвидироваться быстро и незаметно для пользователей.',
    'Conclusion' => 'Заключение',
    'Working with the development team should be convenient and efficient, so you need to approach the choice of an IT partner with full responsibility. Even at the presale stage, you can determine how well the developer suits you, how he cares about the client, how competent his team\'s specialists are and how quickly the team responds to your wishes.' => 'Работа с командой разработчиков должна быть удобной и эффективной, поэтому к выбору IT-партнера нужно подходить со всей ответственностью. Еще на этапе пресейла можно определить, насколько разработчик вам подходит, как он заботится клиенте, насколько специалисты его команды  компетентны и как быстро команда реагирует  на ваши пожелания.',
    'Our technology stack' => 'Наш технологический стек',






];
